package info.omia.animalTalk;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = animalTalk.MODID,version = animalTalk.VERSION)
public class animalTalk {

    public static final String MODID = "animaltalk";
    public static final String VERSION = "0.1";

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event){
        ModMetadata data =event.getModMetadata();
        data.autogenerated=false;
        data.modId = MODID;
        data.name = "Animal Talk";
        data.version = VERSION;
        data.authorList.add("Omia");
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event){

    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event){

    }



}
