package info.omia.animalTalk;

import info.omia.animalTalk.proxy.CommonProxy;
import info.omia.animalTalk.util.handlers.RegisterHandler;
import info.omia.animalTalk.util.reference;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = reference.MODID,version = reference.VERSION)
public class animalTalk {
    @Mod.Instance
    public static animalTalk instance;

    @SidedProxy(clientSide = reference.CLIENT,serverSide = reference.COMMON)
    public static CommonProxy proxy;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event){
        ModMetadata data =event.getModMetadata();
        data.autogenerated=false;
        data.modId = reference.MODID;
        data.name = reference.NAME;
        data.version = reference.VERSION;
        data.authorList.add("Omia");

        RegisterHandler.otherRegistries();
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event){

    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event){

    }



}
